---
title: "Reporte estructura Lansier"
output:
  pdf_document: default
  html_document: default
---
#Análisis con data covid
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(writexl)
library(RODBC)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(fpp2)
# 
# install.packages("archive")
# install.packages("DataExplorer")
# install.packages("fpp2")
sqlcomercial<-odbcConnect("SQLuis",uid = "sa",pwd = "Comercial.2020")

data<-sqlQuery(sqlcomercial,"select * from Venta_Lansier")

data2<-data %>% select(fuente,periodo,cant,subtotal,dpto,distrito,provincia,tipoart,colorequi)
data3<-as.data.frame( trimws(data2$periodo,"b"))
data3$subtotal<-trimws(data2$subtotal,"b")
colnames(data3)<-c("periodo","subtotal")
data3$subtotal<-as.numeric(data3$subtotal)
# convertimos los NA en 0 para poder trabajar mejor sino sale error en las sumas
data3[is.na(data3)] <- 0
# creamos la data agrupada por periodos
data3<-data3 %>% group_by(periodo) %>% summarise(subtotal=sum(subtotal))
data4<-data3[-24,]
data4<-data4[-1,]
# poniendo en formato time series
data5<-data4 %>% select(subtotal)
data5<-data5 %>% mutate(subtotal=subtotal/1000)
data5<-ts(data5,start = c(2020,1),end = c(2021,12),frequency = 12)
```

```{r cars}
autoplot(data5)
ggseasonplot(data5)
ggsubseriesplot(data5)
```

#Análisis sin data covid
